version: 2

defaults: &defaults
  working_directory: /go/src/github.com/sbstjn/github-releases-slack
  docker:
    - image: circleci/golang:latest

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Create .env file
          command: touch .env

      - run:
          name: Install Dependencies
          command: make dependencies

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go"

  test:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Run tests
          command: make test

  build:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Build binary
          command: make build

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
