version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/golang:latest

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: make dependencies

      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'
            - '*.*'

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: make test

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: make build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
