version: 2

defaults: &defaults
  working_directory: /go/src/github.com/sbstjn/github-releases-slack
  docker:
    - image: circleci/golang:latest

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Create .env file
          command: touch .env

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run tests
          command: make test

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Build binary
          command: make build

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
